package cd.project.frontend.soap;

import org.apache.cxf.jaxws.JaxWsProxyFactoryBean;

public class TestClient {
    public static void main(String[] args) {
        JaxWsProxyFactoryBean factory = new JaxWsProxyFactoryBean();

        // Use the URL defined in the soap address portion of the WSDL
        factory.setAddress("http://localhost:8080/frontend/soap/auth");

        // Utilize the class which was auto-generated by Apache CXF wsdl2java
        factory.setServiceClass(Authentication.class);

        Object client = factory.create();
        try {
            // Call the Web Service to perform an operation
            System.out.println("Requesting...");
            String response = ((Authentication)client).authenticate("john", "john");
            System.out.println(response);
        } catch (SecurityException e) {
            e.printStackTrace();
        } catch (IllegalArgumentException e) {
            e.printStackTrace();
        }
    }
}
