services:
  server1:
    image: ghcr.io/al3x-13/cd-backend:latest
    network_mode: host
    environment:
      SERVER_PORT: 1333
    env_file:
      - .env

  server2:
    image: ghcr.io/al3x-13/cd-backend:latest
    network_mode: host
    environment:
      SERVER_PORT: 1334
    env_file:
      - .env

  server3:
    image: ghcr.io/al3x-13/cd-backend:latest
    network_mode: host
    environment:
      SERVER_PORT: 1335
    env_file:
      - .env

  server4:
    image: ghcr.io/al3x-13/cd-backend:latest
    network_mode: host
    environment:
      SERVER_PORT: 1336
    env_file:
      - .env
