PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE users(
id INTEGER PRIMARY KEY AUTOINCREMENT,
username VARCHAR(30) UNIQUE NOT NULL,
password_hash VARCHAR(100) NOT NULL,
session_token VARCHAR(100) UNIQUE
);
INSERT INTO users VALUES(1,'john','$2a$10$LOsnM1XyJ8nUKTA0hQuxN.N6Dw9mDIzZvPA3xb3bfFUOlvnpbxj2e',NULL);
CREATE TABLE beaches(
id char PRIMARY KEY
);
INSERT INTO beaches VALUES('A');
INSERT INTO beaches VALUES('B');
INSERT INTO beaches VALUES('C');
CREATE TABLE bookings(
id INTEGER PRIMARY KEY AUTOINCREMENT,
beach_id CHAR UNIQUE NOT NULL,
lounges_2 INTEGER,
lounges_3 INTEGER,
lounges_4 INTEGER,
from_timestamp TIMESTAMP NOT NULL,
to_timestamp TIMESTAMP NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
user_id INTEGER NOT NULL,
FOREIGN KEY (beach_id) REFERENCES beaches (id),
FOREIGN KEY (user_id) REFERENCES users (id)
);
DELETE FROM sqlite_sequence;
COMMIT;
