name: Publish DB (dev) Docker image

on:
  workflow_dispatch:

jobs:
  push_to_registry:
    name: Push DB (dev) image to Docker Hub
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
        
    - name: Docker Hub login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          
    - name: Build and push DB image
      uses: docker/build-push-action@v2
      with:
        context: ./db
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/cd-db-dev:latest